name: Android Release on Main Merge

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # important for git tag

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Get app version from build.gradle
        id: get_version
        run: |
          VERSION_NAME=$(grep versionName app/build.gradle | head -1 | cut -d '"' -f2)
          echo "VERSION=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ steps.get_version.outputs.VERSION }}
          git push origin v${{ steps.get_version.outputs.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: "Release v${{ steps.get_version.outputs.VERSION }}"
          files: app/build/outputs/apk/release/app-release.apk
